---
- hosts: all
  user: imsalyunus
  become: yess
  become_method: sudo
  become_user: root
  tasks:
    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present
