---
- hosts: all
  become: yes
  user: imsalyunus
  tasks:
    - name: Install server asterisk (state=present is optional)
      ansible.builtin.apt:
        name: asterisk
        state: present
    - name: Hapus file extensions.conf
      ansible.builtin.file:
        path: /etc/asterisk/extensions.conf
        state: absent
    - name: Update repository
      apt_repository:
       repo: 'ppa:git-core/ppa'
       state: present
    - name: Install git
      apt:
       name: git
       state: present
       update_cache: yes
    - name: Download file sip.conf
      ansible.builtin.git:
        repo: 'https://github.com/imsalyunus/asterisk.git'
        dest: /etc/asterisk
           
      
