---
- hosts: all
  become: yes
  user: imsalyunus
  tasks:
    - name: Install server asterisk (state=present is optional)
      ansible.builtin.apt:
        name: asterisk
        state: present
    - name: Hapus file sip.conf & extension.conf
      ansible.builtin.shell: rm /etc/asterisk/sip.conf && rm /etc/asterisk/extension.conf
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/imsalyunus/asterisk.git'
        dest: /etc/asterisk
