---
- hosts: all
  become: yes
  user: imsalyunus
  tasks:
    - name: Install server asterisk (state=present is optional)
      ansible.builtin.apt:
        name: asterisk
        state: present
    - name: Hapus file extension
      file:
        path: /etc/asterisk
      with_items:
        -/etc/asterisk/sip.conf
        -/etc/asterisk/extension.conf
