---
- hosts: all
  become: yes
  user: imsalyunus
  tasks:
    - name: Install server asterisk (state=present is optional)
      ansible.builtin.apt:
        name: asterisk
        state: present
    - name: Hapus file extensions.conf
      ansible.builtin.file:
        path: /etc/asterisk/extensions.conf
        state: absent
    - name: Download file sip.conf
      ansible.builtin.get_url:
        url: 'https://github.com/imsalyunus/asterisk/blob/4d20d11ba3a29b687c6d620abe73cbf6f4d700dc/sip.conf.git'
        dest: /etc/asterisk/
      
