---
- hosts: all
  become: yes
  user: imsalyunus
  tasks:
    - name: Install server asterisk (state=present is optional)
      ansible.builtin.apt:
        name: asterisk
        state: present
    - name: Hapus file extension
      ansible.builtin.file:
        path: /etc/ansible/extensions.conf
        state: absent
