---
- hosts: all
  become: yes
  user: imsalyunus
  tasks:
    - name: Install server asterisk (state=present is optional)
      ansible.builtin.apt:
        name: asterisk
        state: present
    - name: Hapus file extensions.conf
      ansible.builtin.file:
        path: /etc/asterisk/extensions.conf
        state: absent
    - name: Download file sip.conf
      git: repo='https://github.com/imsalyunus/asterisk/blob/1da47c3a08cbbb50cb908a110b66d69e76ab158d/sip.conf'
           dest: /etc/asterisk
      
