#[general]
#allowguest=no
#context=default
#bindport=5060
#dtmfmode=rfc2833
#disallow=all
#allow=alaw
#allow=ulaw
#allow=gsm
#allow=g723
#allow=g726
#allow=speex

[111]
type=friend
host=dynamic
context=testing
username=111
#password=!!!ReplaceWithProperPassword!!!
secret=111
#qualify=yes
#nat=force_rport,comedia

[202]
type=friend
host=dynamic
context=testing
username=112
#password=!!!ReplaceWithProperPassword!!!
secret=112
#qualify=yes
#nat=force_rport,comedia
